general:
  productiveBranch: "main"
  buildTool: "docker"
  dockerConfigJsonSecretTextCredentialsId: "dockerhub"
  containerImageName: "radsoulbeard/frontendui5"
  containerImageTag: &VERSION
  containerRegistryUrl: "https://docker.io"
  verbose: true
steps:
  artifactPrepareVersion:
    dockerVersionSource: "npm"
    filePath: "frontend-ui5-mssql/package.json"
    includeCommitId: false
  kanikoExecute:
    dockerfilePath: "frontend-ui5-mssql/docker/Dockerfile"
  kubernetesDeploy:
    kubeConfigSecretTextCredentialsId: "kubeconfig"
    deployTool: "kubectl"
    namespace: "ui5demo"
    createDockerRegistrySecret: true
    appTemplate: "frontend-ui5-mssql/k8s/deployment.yaml"
stages:
  Build:
    kanikoExecute: true
  Release:
    kubernetesDeploy: true
